#!/usr/bin/env python3
"""
06_generate_tables.py
======================
Generates all 7 paper tables as CSV + LaTeX.

TABLE_01 Per-seed EER/AUC results
TABLE_02 Ablation study
TABLE_03 Protocol comparison
TABLE_04 Per-task-group results
TABLE_05 Statistical tests
TABLE_06 Disentanglement metrics
TABLE_07 Security evaluation (T0-T5)
"""

import os, sys, json
import numpy as np
import csv
from pathlib import Path
sys.path.insert(0, str(Path(__file__).parent))

from config import SEEDS, LOG_DIR, TABLE_DIR, LATEX_DIR


def save_csv(rows, headers, fname):
    Path(TABLE_DIR).mkdir(parents=True, exist_ok=True)
    path = Path(TABLE_DIR) / f"{fname}.csv"
    with open(str(path), 'w', newline='') as f:
        w = csv.DictWriter(f, fieldnames=headers)
        w.writeheader()
        w.writerows(rows)
    return path


def save_tex(rows, headers, fname, caption="", label=""):
    Path(LATEX_DIR).mkdir(parents=True, exist_ok=True)
    path = Path(LATEX_DIR) / f"{fname}.tex"
    col_fmt = "l" + "r" * (len(headers) - 1)
    lines   = []
    lines.append(r"\begin{table}[!t]")
    lines.append(r"\centering")
    if caption:
        lines.append(f"\\caption{{{caption}}}")
    if label:
        lines.append(f"\\label{{{label}}}")
    lines.append(f"\\begin{{tabular}}{{{col_fmt}}}")
    lines.append(r"\hline")
    lines.append(" & ".join(f"\\textbf{{{h}}}" for h in headers) + r" \\")
    lines.append(r"\hline")
    for row in rows:
        lines.append(" & ".join(str(row.get(h, "—")) for h in headers) + r" \\")
    lines.append(r"\hline")
    lines.append(r"\end{tabular}")
    lines.append(r"\end{table}")
    with open(str(path), 'w') as f:
        f.write("\n".join(lines))
    return path


def load_json(path):
    p = Path(path)
    if not p.exists():
        return None
    with open(p) as f:
        return json.load(f)


# ─── TABLE_01: Per-seed results ───────────────────────────────────────────────

def table01_seed_results():
    summary = load_json(Path(LOG_DIR) / "eval_summary.json")
    if summary is None:
        print("  ⚠ TABLE_01: eval_summary.json not found")
        return

    headers = ["Seed", "EER (%)", "AUC", "Note"]
    rows    = []
    for r in summary.get("per_seed", []):
        rows.append({
            "Seed":   r["seed"],
            "EER (%)": f"{r['eer']:.4f}",
            "AUC":    f"{r['auc']:.4f}",
            "Note":   "Best" if r["seed"] == summary.get("best_seed") else ""
        })
    # Append mean row
    rows.append({
        "Seed": "Mean±SD",
        "EER (%)": f"{summary['mean_eer']:.4f}±{summary['std_eer']:.4f}",
        "AUC":    f"{summary['mean_auc']:.4f}±{summary['std_auc']:.4f}",
        "Note":   f"95% CI [{summary['bootstrap_ci'][0]:.4f}, {summary['bootstrap_ci'][1]:.4f}]"
    })

    save_csv(rows, headers, "TABLE_01_seed_results")
    save_tex(rows, headers, "TABLE_01_seed_results",
             caption="Per-seed B2T evaluation results. Mean±SD over 5 seeds.",
             label="tab:seed_results")
    print("  ✓ TABLE_01")


# ─── TABLE_02: Ablation ───────────────────────────────────────────────────────

def table02_ablation():
    # Ablation is generated by running ablation script — create from logs if available
    # Otherwise produce placeholder structure
    headers = ["Configuration", "EER (%)", "AUC", "ΔEER (pp)"]
    rows    = [
        {"Configuration": "Full DOMCS-EEG",          "EER (%)": "—", "AUC": "—", "ΔEER (pp)": "—"},
        {"Configuration": "w/o Orthogonality loss",  "EER (%)": "—", "AUC": "—", "ΔEER (pp)": "—"},
        {"Configuration": "w/o SupCon loss",         "EER (%)": "—", "AUC": "—", "ΔEER (pp)": "—"},
        {"Configuration": "w/o State supervision",   "EER (%)": "—", "AUC": "—", "ΔEER (pp)": "—"},
        {"Configuration": "w/o Dual-space training", "EER (%)": "—", "AUC": "—", "ΔEER (pp)": "—"},
    ]
    # Try to load from ablation logs
    abl_path = Path(LOG_DIR) / "ablation_results.json"
    if abl_path.exists():
        abl = load_json(abl_path)
        if abl:
            rows = []
            full_eer = None
            for entry in abl:
                if entry.get("config") == "Full" or entry.get("config") == "full":
                    full_eer = float(entry.get("eer", 0))
            for entry in abl:
                delta = (float(entry.get("eer",0)) - full_eer) if full_eer else "—"
                rows.append({
                    "Configuration": entry.get("config", "—"),
                    "EER (%)":       f"{float(entry['eer']):.4f}" if entry.get("eer") else "—",
                    "AUC":           f"{float(entry['auc']):.4f}" if entry.get("auc") else "—",
                    "ΔEER (pp)":     f"{delta:+.4f}" if isinstance(delta, float) else "—",
                })

    save_csv(rows, headers, "TABLE_02_ablation")
    save_tex(rows, headers, "TABLE_02_ablation",
             caption="Ablation study: contribution of each loss component.",
             label="tab:ablation")
    print("  ✓ TABLE_02")


# ─── TABLE_03: Protocol comparison ───────────────────────────────────────────

def table03_protocol():
    headers = ["Protocol", "Enrollment", "Test", "EER (%)", "Note"]
    rows    = [
        {"Protocol": "Same-session",  "Enrollment": "80% per-run", "Test": "20% per-run",
         "EER (%)": "—", "Note": "Upper bound (easiest)"},
        {"Protocol": "Random-split",  "Enrollment": "80% all",     "Test": "20% all",
         "EER (%)": "—", "Note": "No session boundary"},
        {"Protocol": "B2T (proposed)","Enrollment": "R01+R02",     "Test": "R03–R14",
         "EER (%)": "—", "Note": "Realistic deployment"},
        {"Protocol": "Approach② event", "Enrollment":"R01+R02",   "Test": "Task-only (event)",
         "EER (%)": "—", "Note": "State-invariance ②"},
        {"Protocol": "Approach③ event", "Enrollment":"R01+R02",   "Test": "Rest-only (event)",
         "EER (%)": "—", "Note": "State-invariance ③"},
    ]
    # Populate B2T EER from eval_summary
    summary = load_json(Path(LOG_DIR) / "eval_summary.json")
    if summary:
        for r in rows:
            if r["Protocol"] == "B2T (proposed)":
                r["EER (%)"] = f"{summary['mean_eer']:.4f}±{summary['std_eer']:.4f}"

    save_csv(rows, headers, "TABLE_03_protocol_comparison")
    save_tex(rows, headers, "TABLE_03_protocol_comparison",
             caption="Protocol comparison — enrollment and verification data sources.",
             label="tab:protocol")
    print("  ✓ TABLE_03")


# ─── TABLE_04: Per-task results ───────────────────────────────────────────────

def table04_per_task():
    summary = load_json(Path(LOG_DIR) / "eval_summary.json")
    headers = ["Task Group", "Runs", "EER (%)", "AUC", "N probes"]
    rows    = []

    task_info = {
        "RL_Fist_MI":  "R03,R07,R11",
        "BF_Feet_MI":  "R04,R08,R12",
        "RL_Fist_MV":  "R05,R09,R13",
        "BF_Feet_MV":  "R06,R10,R14",
    }

    if summary:
        grp_eers = {}
        grp_aucs = {}
        grp_n    = {}
        for seed_res in summary.get("per_seed", []):
            for grp, val in seed_res.get("per_task_group", {}).items():
                if val.get("eer") is not None:
                    grp_eers.setdefault(grp, []).append(val["eer"])
                    grp_aucs.setdefault(grp, []).append(val.get("auc", np.nan))
                    grp_n[grp] = val.get("n_probes", "—")
        for grp, runs_str in task_info.items():
            eers = grp_eers.get(grp, [])
            aucs = grp_aucs.get(grp, [])
            rows.append({
                "Task Group": grp.replace("_"," "),
                "Runs":       runs_str,
                "EER (%)":    f"{np.mean(eers):.4f}±{np.std(eers):.4f}" if eers else "—",
                "AUC":        f"{np.nanmean(aucs):.4f}" if aucs else "—",
                "N probes":   grp_n.get(grp, "—"),
            })
    else:
        for grp, runs_str in task_info.items():
            rows.append({"Task Group": grp.replace("_"," "), "Runs": runs_str,
                         "EER (%)": "—", "AUC": "—", "N probes": "—"})

    save_csv(rows, headers, "TABLE_04_per_task_results")
    save_tex(rows, headers, "TABLE_04_per_task_results",
             caption="Per-task-group EER — cross-state verification results.",
             label="tab:per_task")
    print("  ✓ TABLE_04")


# ─── TABLE_05: Statistical tests ─────────────────────────────────────────────

def table05_stats():
    summary = load_json(Path(LOG_DIR) / "eval_summary.json")
    headers = ["Metric", "Value"]
    rows    = []
    if summary:
        rows = [
            {"Metric": "Mean EER (%)",     "Value": f"{summary['mean_eer']:.4f}"},
            {"Metric": "Std EER (%)",      "Value": f"{summary['std_eer']:.4f}"},
            {"Metric": "Mean AUC",         "Value": f"{summary['mean_auc']:.4f}"},
            {"Metric": "95% CI (n=10000)", "Value": f"[{summary['bootstrap_ci'][0]:.4f}, {summary['bootstrap_ci'][1]:.4f}]"},
            {"Metric": "Wilcoxon stat",    "Value": f"{summary.get('wilcoxon_stat', '—')}"},
            {"Metric": "Wilcoxon p-value", "Value": f"{summary.get('wilcoxon_p', '—')}"},
            {"Metric": "Best seed",        "Value": str(summary.get('best_seed','—'))},
        ]
    save_csv(rows, headers, "TABLE_05_statistical_tests")
    save_tex(rows, headers, "TABLE_05_statistical_tests",
             caption="Statistical analysis of EER across 5 seeds.",
             label="tab:stats")
    print("  ✓ TABLE_05")


# ─── TABLE_06: Disentanglement metrics ────────────────────────────────────────

def table06_disentanglement():
    dis = load_json(Path(LOG_DIR) / "disentanglement_metrics.json")
    headers = ["Metric", "Value", "Expected", "Status"]
    rows    = []

    if dis:
        def avg(key):
            vals = [m[key] for m in dis if m and key in m]
            return np.mean(vals) if vals else None
        def avg_nested(outer, inner):
            vals = [m[outer][inner] for m in dis if m and outer in m]
            return np.mean(vals) if vals else None

        r = [
            ("z_id → Subject probe",   avg_nested("zid_subject_probe","acc"),   "> 0.90", None),
            ("z_id → State probe",     avg_nested("zid_state_probe","acc"),     "≈ chance", None),
            ("z_state → Subject probe",avg_nested("zstate_subject_probe","acc"),"≈ chance", None),
            ("z_state → State probe",  avg_nested("zstate_state_probe","acc"),  "> 0.50", None),
            ("Orthogonality (mean|cos|)", avg("orth_mean_cosine"),              "≈ 0", None),
            ("MI(z_id, Subject)",      avg("mi_zid_subject"),                   "HIGH", None),
            ("MI(z_id, State)",        avg("mi_zid_state"),                     "LOW", None),
            ("Sil(z_id, Subject)",     avg("sil_zid_subject"),                  "> 0", None),
            ("Sil(z_id, State)",       avg("sil_zid_state"),                    "< 0", None),
            ("Sil(z_state, State)",    avg("sil_zstate_state"),                 "> 0", None),
            ("z_id intra-subj cosine", avg("zid_intra_subject_cos"),            "HIGH", None),
            ("z_id inter-subj cosine", avg("zid_inter_subject_cos"),            "≈ 0", None),
        ]
        for (metric, val, expected, _) in r:
            val_str = f"{val:.4f}" if val is not None else "—"
            rows.append({
                "Metric":   metric,
                "Value":    val_str,
                "Expected": expected,
                "Status":   "✓" if val is not None else "—"
            })
    else:
        rows = [{"Metric": "Run 05_disentanglement_analysis.py first",
                 "Value": "—", "Expected": "—", "Status": "—"}]

    save_csv(rows, headers, "TABLE_06_disentanglement_metrics")
    save_tex(rows, headers, "TABLE_06_disentanglement_metrics",
             caption="Disentanglement metrics from linear probes, MI, orthogonality, and silhouette.",
             label="tab:disentangle")
    print("  ✓ TABLE_06")


# ─── TABLE_07: Security evaluation ────────────────────────────────────────────

def table07_security():
    sec = load_json(Path(LOG_DIR) / "security_eval_results.json")
    headers = ["Threat", "Description", "EER (%)", "AUC", "TSR (%)"]
    rows    = []

    if sec:
        for r in sec.get("results", []):
            rows.append({
                "Threat":       r.get("label", "—"),
                "Description":  "",
                "EER (%)":      f"{r['eer']:.3f}" if r.get("eer") is not None else "—",
                "AUC":          f"{r['auc']:.4f}" if r.get("auc") is not None else "—",
                "TSR (%)":      f"{r['tsr']:.2f}" if r.get("tsr") is not None else "—",
            })
    else:
        rows = [{"Threat": "Run 04_security_analysis.py first",
                 "Description": "", "EER (%)": "—", "AUC": "—", "TSR (%)": "—"}]

    save_csv(rows, headers, "TABLE_07_security_results")
    save_tex(rows, headers, "TABLE_07_security_results",
             caption="Security evaluation — T0 through T5 threat model results.",
             label="tab:security")
    print("  ✓ TABLE_07")


def main():
    print("DOMCS-EEG — Table Generation")
    print("="*60)
    table01_seed_results()
    table02_ablation()
    table03_protocol()
    table04_per_task()
    table05_stats()
    table06_disentanglement()
    table07_security()
    print(f"\n  CSV: {TABLE_DIR}")
    print(f"  TEX: {LATEX_DIR}")


if __name__ == "__main__":
    main()
